name: Deploy App Folder to SFTP

on:
  push:
    branches:
      - main  # or your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: npm install && npm run build
        # Make sure this builds into app/build

      - name: Install SSH and SFTP clients
        run: sudo apt-get install sshpass openssh-client

      - name: Deploy 'app/build' folder to SFTP server
        env:
          SSHPASS: ${{ secrets.SFTP_PASSWORD }}
        run: |
          sshpass -e sftp -oBatchMode=no -oStrictHostKeyChecking=no -b - -oPort=${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} <<< $'put -r app/build /'


